version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=rau
    ports:
      - 3306:3306

  app:
    image: ra-backend-image
    ports:
      - 8888:8888
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/rau?autoReconnect=true&useSSL=false
      WAIT_HOSTS: docker-mysql:3306
    depends_on:
      - docker-mysql

  web:
    image: ra-frontend-image
    ports:
      - 80:80
    depends_on:
      - app   
